### ISSUE TITLE
APIサーバーのGKEかGCEかの技術検証

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#12]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by corentytakeshi** [comment]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by corentytakeshi** [comment]
@kou0123 
Dockerを使用するためGKEを使用する方針とします。

違和感あればコメントおねがいー
なければクローズをお願いー

**Comment by kou0123** [comment]
調査ありがとうございました。長い間放置してすいませんでした。
github issueのコメントとslackを連携させたため、これからはガンガン確認できます。
