### ISSUE TITLE
travis testをdockerで動かす調査

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#14]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by kou0123** [comment]
## dockerの仕様有無

1.本番環境と同じdockerを使うため、それぞれのメンテナンスが一括に可能。
学習コストはあるものの、拡張性は高いとおもわれる。
2.travisの初回学習コストのみ
3. 金はかからない。が将来的にはmaster/slave構成にしないとつらそう。
4. コア要件とはCI/CDで自動テストを実行することである。それがdockerで可能か。
結論可能である。travisからのdockerfileがbuildされ、その時に、gradle.buildがおこなわれ、
単体テストが実行されることになる。

## 関連URL
https://qiita.com/gongo/items/fd02249ee8976652cd2d

## TODO
- dockerでの構築
- ISSUEテンプレートをつくる
- ISSUEの積極的活用

**Comment by corentytakeshi** [comment]
TODOが #19 #20 に切られていることを確認しました。
