### ISSUE TITLE
stackdriverの技術検証

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#16]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by corentytakeshi** [comment]
memo
2、運用コスト(金)
https://cloud.google.com/stackdriver/pricing?hl=ja

**Comment by corentytakeshi** [comment]
memo
- Stackdriverの全体感を掴む資料
https://www.topgate.co.jp/gcp15-what-is-google-stackdriver

**Comment by corentytakeshi** [comment]
memo

stackdriverの技術検証というより、そもそも何が実現したいのかがよくわかっていない。
ログの解析は必要なのが、クラッシュレポートは必要なのか、Ph1.0で実施するのは必須条件なのかを明確にする必要があると考えている。

**Comment by corentytakeshi** [comment]
@kou0123 
チケット内容の確認をお願いします。
全体の方針は改めて決めましょう。

**Comment by corentytakeshi** [comment]
@kou0123 
Ph1.0では実装しない方針として進めます。

理由は下記
- Ph1.0はミニマムで実装するため
- ユーザが多くなり、APIのレイテンシー等の性能問題が発生したら実装する

**Comment by corentytakeshi** [comment]
@kou0123 
下記の公式ドキュメントを確認したところ
GCPのCloud Audit Logging ログは無料と記載されているので、どこまで無料でみれて、どこまで見れないのかを検証する必要があるので
やっぱり、構築する前提ですすみまーす
https://cloud.google.com/stackdriver/pricing?hl=ja#logging-costs

**Comment by kou0123** [comment]
OK
