### ISSUE TITLE
CloudSQLかGCEのmysqlの技術検証

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#17]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by corentytakeshi** [comment]
調べたこと
- CloudSQLの料金
https://cloud.google.com/sql/pricing?hl=ja

- MySQLの構築手順
https://centossrv.com/mysql.shtml

- MySQLとOraclenの差
https://www.slideshare.net/ryotawatabe/20161109-oracle-engineer-mysql-casual-fukuoka6

**Comment by corentytakeshi** [comment]
今見えているメリット
- 監視構築コストがいらない(モニタリング機能があり、スループット等がみれる)
- バックアップが自動
- メンテナンスが不要(再起動とか勝手にやってくれる)
- フェイルオーオーバーが標準で行える

**Comment by corentytakeshi** [comment]
今見えているデメリット
- 課金制(料金が固定されない、いくらかかるのか明確じゃない)
- CPU等のスペックが低い(同じ料金くらいのGCEを立てた時のcpu,ram,storage等と比較するとスペックが下がる)

**Comment by corentytakeshi** [comment]
CloudSQL
1、拡張性
CPU,RAM,Storageの拡張性は高い
とくに、DBの直接的な使用量によって拡張させることができる

2、運用コスト(人)
低い。モニタリング機能、自動メンテナンス、GCPコンソールのUI操作ができることにより運用コストは低い。

2、運用コスト(金)
不明。アプリで使用するcpu,ram,storageが正確に見積もれてないため、不明。

3、導入コスト(人)
低い。UI操作でのインスタンスの作成が可能

4、コア要件を満たせるかどうか？
MySQL,CloudSQL共に満たす

**Comment by corentytakeshi** [comment]
MySQL
1、拡張性
GCEを使用する場合、CPU,RAM,Storageの拡張性は高い
一方で、GCEにdbを構築するため、拡張させる時、dbの原因なのか、別の要因なのかの判別を行う必要がある

2、運用コスト(人)
高い。バックアップの管理、スループットモニタリング等を構築する必要がある

2、運用コスト(金)
不明。DBで使用するcpu,ram,storageが正確に見積もれてないため、不明。

3、導入コスト(人)
高い。バックアップ、モニタリング、フェイルオーバーの設定を構築する必要がある

4、コア要件を満たせるかどうか？
MySQL,CloudSQL共に満たす

**Comment by corentytakeshi** [comment]
@kou0123
CloudSQLもMySQLも運用コスト(金)が不確定なことから、導入しやすいCloudSQLをミニマムで構築し、必要なスペック感、価格感を見ていきたいと思います。

違和感、気になる点あれば言ってください！！

**Comment by kou0123** [comment]
ありがとう御座いました。お疲れ様です。

こちら拝見しましたところ、cloudsqlの方が、運用コスト（金）以外はメリットが高そうな印象をうけました。

あと、mysqlで構築した場合、スループットモニタリング、バックアップ、フェイルオーバーの仕組みを構築するコストがかかってくるので、

総合的に判断すると、cloudsqlで舵を切る方向で良いと思いました。

では、構築検証をよろしくお願いします。
お手数おかけしますが、よろしくお願いします。

**Comment by corentytakeshi** [comment]
@kou0123 
ごめん
料金の見積もりがミスっていました。
年間でCloudSQLは9万円程度、GCEでMySQLを構築すると4万円程度
そのため、年間5万円の差があるのでCostをできる限り削減する観点から、GCEでMySQLを構築する方針とします。
