### ISSUE TITLE
レコメンドのAPIサーバーの技術検証

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#18]
技術検証観点
1、拡張性
2、運用コスト(人)
2、運用コスト(金)
3、導入コスト(人)
4、コア要件を満たせるかどうか？

**Comment by kou0123** [comment]
## 調査結果
- たまたま、AIサーバーについて知る機会があったため記載。
- 業界のスタンダードはpython の flaskフレームワークである (軽量なため)
- flaskフレームワークから、学習済みモデルをimportする。
- deeplearning系だとAPIサーバーにGPUを載せる必要がある (大量の計算処理をするため)

##  関連URL
[【図解】なぜGPUはディープラーニング・AI開発に向いているの？選び方は？NVIDIAさんに聞いてきました | カゴヤのサーバー研究室](https://www.kagoya.jp/howto/rentalserver/gpu_deeplearning_ai/)

**Comment by kou0123** [comment]
- 1、拡張性
2、
3、
4、
5、

**Comment by kou0123** [comment]
## TODO
- 橋本、岡本以外の他メンバーへのタスクの積極的な配布

**Comment by corentytakeshi** [comment]
@kou0123 
AI側のAPIサーバについては、1stリリース時はローカル環境で実施する。
(ユーザ数やデータ数が、サーバが必要になる程多くないと見積もっているため)
そのため、サーバ構築に関しては保留
