### ISSUE TITLE
google maps api 技術検証

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#2]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
- tokyolunchの要となる飲食店の情報を取得する方法を調査する

## ゴール
- なんの情報が取れるのか、価格感を調査する
- GoogleAPIがダメだった場合の代替手段を調査する

## 関連するURL
- 参考文献や調査資料を書いてください。

**Comment by corentytakeshi** [comment]
参考
https://qiita.com/Haruka-Ogawa/items/997401a2edcd20e61037

**Comment by corentytakeshi** [comment]
参考
https://developers.google.com/places/android-sdk/place-details?hl=ja

**Comment by corentytakeshi** [comment]
参考
- 料金プラン、課金プラン
https://developers.google.com/places/web-service/usage-and-billing?hl=ja

**Comment by corentytakeshi** [comment]
参考
- 料金表
https://cloud.google.com/maps-platform/pricing/sheet/?hl=ja&__utma=102347093.1588615514.1553136523.1553144810.1553144810.1&__utmb=102347093.0.10.1553144810&__utmc=102347093&__utmx=-&__utmz=102347093.1553144810.1.1.utmcsr=oar.st40.xyz|utmccn=(referral)|utmcmd=referral|utmcct=/article/253&__utmv=-&__utmk=221842584&_ga=2.244940037.1231193489.1553136523-1588615514.1553136523#places

**Comment by corentytakeshi** [comment]
参考
- 実際にAPIを使用した例
https://www.monotalk.xyz/blog/Use-the-Google-Place-API-as-a-facility-search-API/

**Comment by corentytakeshi** [comment]
参考
- 実際にAPIを使用した例2 こっちは具体例が書かれている
https://diy-kagu.hatenablog.com/entry/2018/07/14/110644

**Comment by corentytakeshi** [comment]
参考
- 実際にAPIを使用した例3 こっちも具体例が書かれている
https://nacl-ltd.github.io/2017/02/17/place-search-api.html

**Comment by corentytakeshi** [comment]
GoogleMapAPIで可能なこと
- 指定した緯度、経度から、指定した範囲の施設を検索
- PlaceTypeをrestaurantと指定することで、飲食店の情報に限定して情報を取得する
- 取得できる情報はBasic Dataを参照
https://developers.google.com/maps/billing/understanding-cost-of-use?hl=ja#basic-data
- 料金は毎月$200分まで無料
- $200分を超えたらリクエストに対して課金となる。課金料金は下記参照
https://cloud.google.com/maps-platform/pricing/sheet/?hl=ja&__utma=102347093.1588615514.1553136523.1553144810.1553144810.1&__utmb=102347093.0.10.1553144810&__utmc=102347093&__utmx=-&__utmz=102347093.1553144810.1.1.utmcsr=oar.st40.xyz%7Cutmccn=(referral)%7Cutmcmd=referral%7Cutmcct=/article/253&__utmv=-&__utmk=221842584&_ga=2.244940037.1231193489.1553136523-1588615514.1553136523#places

TODO
- $200分の定義が不明なため実際に使ってみることで確認する

まとめ
- TODOで東京ランチでGoogleMapAPIを使用した場合の価格感を検証する
- TODO次第ではあるが、1日に最大15,000のリクエストは無料のため(決め打ちで)GoogleMapAPIを使用する前提で開発を進める

**Comment by corentytakeshi** [comment]
@ritsuki-fujisaki @kou0123 
GoogleMapAPI使う方針で動きたいと思います。
気になる点あれば、コメントお願いします。
別チケットで対応します。

**Comment by kou0123** [comment]
issueにlogを残すのは素晴らしい方法ですね。とても参考になりました。ありがとう御座いました。

**Comment by kou0123** [comment]
内容としては対面でも確認しているのでクローズします。
