### ISSUE TITLE
ISSUEテンプレートを作る

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#20]

**Comment by kou0123** [comment]
## ゴール
- taskが回りやすいようにissueテンプレートを作成する

**Comment by corentytakeshi** [comment]
@kou0123 
こちらチケットのゴール満たしていると思っているので、認識齟齬なかったらクローズしちゃってください。

**Comment by kou0123** [comment]
- dev yuraku-b yuraku-a yuraku-i bizにISSUE テンプレートを作成しました。
- 対面にて確認済みです。
