### ISSUE TITLE
全メンバーへのタスクの積極的な配布

### ISSUE THREAD

**Issue by kou0123** [tokyoLunch/dev#22]
## 目的
- タスクにアサインのないメンバーがいるため
- 人材の有効活用

## ゴール
- 全メンバーが1週間は動けるタスクを作成する
- 全メンバーがタスクボードを使用している状態にする。
- 全アサインタスクにおいて担当者に頭出し、説明する。

**Comment by kou0123** [comment]
@corentytakeshi さん
こちら気になっているので、どう対応するか話しましょう。

**Comment by corentytakeshi** [comment]
@kou0123 
了解ー

タスクにアサインがないだけで、裏ではうご入れくれているってパターンもあると思うから

- タスクの洗い出し
- タスクの見える化

という点で対応を考えましょう

**Comment by kou0123** [comment]
了解しました!

**Comment by corentytakeshi** [comment]
@kou0123 
タスクについてはissue化とSlackのTODO化ができているのでこのチケットとしてはクローズでいいかなと思うのですが、どうでしょう

**Comment by kou0123** [comment]
上記了解しました。
このチケットはクローズします
ありがとう御座いました。
