### ISSUE TITLE
アプリケーションアーキテクチャの検討と実装

### ISSUE THREAD

**Issue by corentytakeshi** [tokyoLunch/dev#24]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
- Tokyolunchにおけるアプリケーションアーキテクチャを実装する。

## ゴール
- 決定したアーキテクチャの実装が行われていること
- WIKI等でアーキテクチャの目的、説明が記載されていること
- 開発メンバーに説明が行われていること

## 関連するURL
- 参考文献や調査資料を書いてください。

**Comment by kou0123** [comment]
## サーバー
- サーバー側はclean airchiでパッケージを分割する。

-adapter
  - controller　エンドポイント
  - repository　DBアクセス
  - presenter フロントへ返す値の加工
  - resorce リクエストやレスポンスのdto
- usecase 業務処理を記載
- entity dbから取得した値をそのままマッピングする

依存関係はadapter→usecase→entity
矢印が逆転する場合はインターフェイスに依存させることにより、依存性をなくし、解決する。

**Comment by kou0123** [comment]
wikiの開発ガイドに記載する

**Comment by corentytakeshi** [comment]
ログインでやるため、クローズ
