### ISSUE TITLE
GKEの構築を行う

### ISSUE THREAD

**Issue by corentytakeshi** [tokyoLunch/dev#31]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
- https://github.com/tokyoLunch/dev/issues/12
- 上記チケットの方針により、GKEの構築を行う

## ゴール
- GKEの構築が完了すること。
- Dockerによるアプリのデプロイ、アプリの起動が行えること。

## 関連するURL
- 参考文献や調査資料を書いてください。

**Comment by corentytakeshi** [comment]
手順を作成しました。

https://github.com/tokyoLunch/dev/wiki/Docker%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86

**Comment by corentytakeshi** [comment]
@kou0123 
レビューおなしゃす

**Comment by kou0123** [comment]
OK
ロードバランサーはきっといてもいいかもね
